"""Add username column to users table

Revision ID: aad0561deaac
Revises: 
Create Date: 2024-11-16 16:46:54.017823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aad0561deaac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('blogs', 'body',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'password')
    op.alter_column('blogs', 'body',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('blogs', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
